name: xylophone_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.7.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/shortSounds/do.mp4
    - assets/shortSounds/re.mp4
    - assets/shortSounds/mi.mp4
    - assets/shortSounds/fa.mp4
    - assets/shortSounds/sol.mp4
    - assets/shortSounds/la.mp4
    - assets/shortSounds/si.mp4

    - assets/longSounds/undead.mp3
    - assets/longSounds/wolf.mp3
    - assets/longSounds/chicks.mp3
    - assets/longSounds/elephant.mp3
    - assets/longSounds/frog.mp3
    - assets/longSounds/monkeys.mp3
    - assets/longSounds/peacock.mp3

    - assets/img/chicken.png
    - assets/img/elephant-side-view.png
    - assets/img/monkey-facing-right.png
    - assets/img/wolf.png
    - assets/img/wolf-howling-at-the-moon.png
    - assets/img/tropical-frop.png
    - assets/img/peacock.png
    - assets/img/umbrella.png
  fonts:
    - family: FrederickatheGreat
      fonts:
        - asset: fonts/FrederickatheGreat-Regular.ttf



